# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kOGyklln1ZrCJ4qRPDgBDEngPqMNdsW9
"""

!pip install gtts

from gtts import gTTS
import os


text ="Hi students what's up.Can you help me?"


language = 'en'
tts = gTTS(text=text, lang=language, slow=False)


audio_file = "ovoz.mp3"
tts.save(audio_file)


from IPython.display import Audio
Audio(audio_file)

from gtts import gTTS
import os


text ="Look at me teacher"


language = 'en'
tts = gTTS(text=text, lang=language, slow=False)


audio_file = "ovoz.mp3"
tts.save(audio_file)


from IPython.display import Audio
Audio(audio_file)

from gtts import gTTS
import os


text ="The best player of the world Leonel Andres Messi"


language = 'en'
tts = gTTS(text=text, lang=language, slow=False)


audio_file = "ovoz.mp3"
tts.save(audio_file)


from IPython.display import Audio
Audio(audio_file)

import numpy as np
import matplotlib.pyplot as plt
from scipy.io import wavfile

def generate_spectrogram(wav_file):

    sample_rate, data = wavfile.read(wav_file)


    if len(data.shape) > 1:
        data = data[:, 0]
    plt.figure(figsize=(12, 6))
    plt.specgram(data, Fs=sample_rate, NFFT=1024, noverlap=512, cmap='inferno')

    plt.title(f'Spectrogram of {wav_file}')
    plt.xlabel('Time (s)')
    plt.ylabel('Frequency (Hz)')
    plt.colorbar(label='Intensity (dB)')
    plt.xlim(0, len(data) / sample_rate)
    plt.ylim(0, sample_rate / 2)
    plt.grid(True)
    plt.show()


wav_file_path = 'fireworks-peony-260343.wav'
generate_spectrogram(wav_file_path)

import numpy as np
import matplotlib.pyplot as plt
from scipy.io import wavfile

def generate_spectrogram(wav_file):

    sample_rate, data = wavfile.read(wav_file)

    if len(data.shape) > 1:
        data = data[:, 0]
    plt.figure(figsize=(12, 6))
    plt.specgram(data, Fs=sample_rate, NFFT=1024, noverlap=512, cmap='inferno')

    plt.title(f'Spectrogram of {wav_file}')
    plt.xlabel('Time (s)')
    plt.ylabel('Frequency (Hz)')
    plt.colorbar(label='Intensity (dB)')
    plt.xlim(0, len(data) / sample_rate)
    plt.ylim(0, sample_rate / 2)
    plt.grid(True)
    plt.show()


wav_file_path = 'fireworks-peony-260343.wav'
generate_spectrogram(wav_file_path)

import numpy as np
import matplotlib.pyplot as plt
from scipy.io import wavfile

def generate_spectrogram(wav_file):

    sample_rate, data = wavfile.read(wav_file)


    if len(data.shape) > 1:
        data = data[:, 0]


    plt.figure(figsize=(12, 6))
    plt.specgram(data, Fs=sample_rate, NFFT=1024, noverlap=512, cmap='inferno')

    plt.title(f'Spectrogram of {wav_file}')
    plt.xlabel('Time (s)')
    plt.ylabel('Frequency (Hz)')
    plt.colorbar(label='Intensity (dB)')
    plt.xlim(0, len(data) / sample_rate)
    plt.ylim(0, sample_rate / 2)
    plt.grid(True)
    plt.show()


wav_file_path = 'pianos-by-jtwayne-7-174717.wav'
generate_spectrogram(wav_file_path)